# Generated by Django 2.2 on 2019-04-05 12:18

import amazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', amazon.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='', verbose_name='サムネイル'),
            preserve_default=False,
        ),
    ]
