# Generated by Django 2.2 on 2019-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20190405_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='サムネイル'),
        ),
    ]
