# Generated by Django 2.2 on 2019-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_auto_20190406_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
